# Generated by Django 4.1.5 on 2024-03-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=500, unique=True)),
                ('file_url', models.CharField(blank=True, max_length=250, null=True)),
                ('summarized_file_url', models.CharField(blank=True, max_length=250, null=True)),
                ('gener', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.IntegerField()),
                ('img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
            },
        ),
    ]
