# Generated by Django 4.1.5 on 2024-03-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_owner_id'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
