# Generated by Django 5.0.6 on 2024-05-30 18:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('is_channel', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('chats', models.ManyToManyField(blank=True, related_name='chats', to='utils.chat')),
                ('clubs', models.ManyToManyField(blank=True, related_name='members', related_query_name='member', to='club.club')),
                ('friends', models.ManyToManyField(to='utils.user')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.chat')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.user')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='utils.user'),
        ),
    ]
