# Generated by Django 4.1.5 on 2024-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_roadmapweek_roadmap_id_clubreview'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='members', related_query_name='member', to='club.club'),
        ),
    ]
