# Generated by Django 5.0.6 on 2024-05-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=500, unique=True)),
                ('type', models.CharField(max_length=250)),
                ('img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('current_capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('rating', models.FloatField(default='0.0')),
                ('category', models.CharField(default='General', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='UserRoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=250)),
                ('cover_url', models.CharField(blank=True, max_length=250, null=True)),
                ('club_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ClubReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500, unique=True)),
                ('rating', models.FloatField(default='0.0')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='club.club')),
            ],
            options={
                'verbose_name': 'ClubReview',
                'verbose_name_plural': 'ClubReviews',
                'db_table': 'club_review',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_count', models.IntegerField()),
                ('weeks_capacity', models.IntegerField()),
                ('club', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='club.club')),
            ],
            options={
                'verbose_name': 'Roadmap',
                'verbose_name_plural': 'Roadmaps',
                'db_table': 'roadmap',
            },
        ),
        migrations.CreateModel(
            name='RoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='club.roadmap')),
            ],
            options={
                'verbose_name': 'RoadmapWeek',
                'verbose_name_plural': 'RoadmapWeeks',
                'db_table': 'roadmap_week',
            },
        ),
    ]
