# Generated by Django 4.1.5 on 2024-03-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=500, unique=True)),
                ('type', models.CharField(max_length=250)),
                ('img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('current_capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_count', models.IntegerField()),
                ('weeks_capacity', models.IntegerField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'verbose_name': 'Roadmap',
                'verbose_name_plural': 'Roadmaps',
                'db_table': 'roadmap',
            },
        ),
        migrations.CreateModel(
            name='RoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('degree', models.IntegerField()),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=500, unique=True)),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.roadmap')),
            ],
            options={
                'verbose_name': 'RoadmapWeek',
                'verbose_name_plural': 'RoadmapWeeks',
                'db_table': 'roadmap_week',
            },
        ),
    ]
