# Generated by Django 5.0.6 on 2024-05-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroadmapweek',
            options={'verbose_name': 'UserRoadmapWeek', 'verbose_name_plural': 'UserRoadmapWeeks'},
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubreview',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmapweek',
            name='users_progress',
            field=models.ManyToManyField(related_name='weeks_progress', through='club.UserRoadmapWeek', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroadmapweek',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userroadmapweek',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userroadmapweek',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userroadmapweek',
            name='week_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.roadmapweek'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='userroadmapweek',
            table='user_roadmap_week',
        ),
    ]
