# Generated by Django 5.0.6 on 2024-06-01 15:57

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_userroadmapweek_options_club_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='rating',
            field=models.FloatField(default=club.models.generate_random_rating),
        ),
    ]
