# Generated by Django 4.1.5 on 2024-03-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='rating',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='roadmapweek',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
