# Generated by Django 4.1.5 on 2024-03-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_rating_roadmapweek_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
