# Generated by Django 4.1.5 on 2024-03-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_rename_owner_id_club_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='club_id',
        ),
        migrations.AddField(
            model_name='club',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.roadmap'),
        ),
    ]
