# Generated by Django 5.0.6 on 2024-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_club_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='rating',
            field=models.FloatField(default='0.0'),
        ),
    ]
