# Generated by Django 4.1.5 on 2024-03-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_roadmapweek_roadmap_id_clubreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='roadmap',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='club.club'),
        ),
    ]
