# Generated by Django 4.1.5 on 2024-03-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_remove_club_roadmap_roadmap_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='club',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='club.club'),
        ),
    ]
