# Generated by Django 4.1.5 on 2024-03-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_user_clubs'),
        ('club', '0008_alter_roadmap_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapweek',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='UserRoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.user')),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.roadmapweek')),
            ],
            options={
                'verbose_name': 'UserRoadmapWeek',
                'verbose_name_plural': 'UserRoadmapWeeks',
                'db_table': 'user_roadmap_week',
            },
        ),
        migrations.AddField(
            model_name='roadmapweek',
            name='users_progress',
            field=models.ManyToManyField(related_name='weeks_progress', through='club.UserRoadmapWeek', to='utils.user'),
        ),
    ]
