# Generated by Django 4.1.5 on 2024-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_remove_roadmapweek_is_completed_userroadmapweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapweek',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='roadmapweek',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
