# Generated by Django 4.1.5 on 2024-05-25 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_userroadmapweek_is_in_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=250)),
                ('cover_url', models.CharField(blank=True, max_length=250, null=True)),
                ('club_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
            },
        ),
    ]
